// app/boutique/data.ts
export type Product = {
  slug: string
  title: string
  price: string
  image: string
  summary: string
  chapters: string[]
  group: "t1" | "t2"
}

export const products: Product[] = [
  {
    slug: "introduction-aux-guides",
    title: "Introduction to the psychological guides",
    price: "$9.50",
    image: "/introduction.jpg",
    summary: "Foundations of the approach: therapy as training to become the healer of your world.",
    chapters: [
      "Foreword",
      "Introduction",
      "The practice of therapy",
      "What is the subject",
      "Therapy where you are the hero",
      "The fundamental limit",
    ],
    group: "t2",
  },
  {
    slug: "estime-de-soi",
    title: "Self-esteem",
    price: "$9.50",
    image: "/estime.jpg",
    summary: "Leave narcissism to recover the tension of desire and decentering practices.",
    chapters: [
      "Introduction",
      "The mirage of the self",
      "Narcissism and false autonomy",
      "Recovering the tension of desire",
      "Practices that decenter",
      "Conclusion",
    ],
    group: "t2",
  },
  {
    slug: "depression",
    title: "Depression",
    price: "$9.50",
    image: "/depression.jpg",
    summary: "Read depression as protective withdrawal. Reopen the path through tiny beginnings and supports.",
    chapters: [
      "Introduction",
      "The slowed body",
      "Thinking that closes",
      "Isolation and connection",
      "Obscure desire and life that persists",
      "Small movements, tiny starts",
      "Supports and companionship",
      "Conclusion",
    ],
    group: "t1",
  },
  {
    slug: "anxiete",
    title: "Anxiety",
    price: "$9.50",
    image: "/anxiete.jpg",
    summary: "From bodily signal to thought loops: receive the wave and regain room for action.",
    chapters: [
      "Introduction",
      "When the body speaks",
      "The circle of thoughts",
      "Giving worry a place",
      "Meeting others",
      "Desire, choice, the unexpected",
      "Concrete tracks",
      "Conclusion",
    ],
    group: "t1",
  },
  {
    slug: "relations-amoureuses",
    title: "Romantical relationships",
    price: "$9.50",
    image: "/relations.jpg",
    summary: "Desire as a living gap: speech, daily seduction, positions and freedom in the bond.",
    chapters: [
      "Desire and encounter",
      "The art of speech",
      "Everyday seduction",
      "Balance beyond 50/50",
      "Position games",
      "Freedom and bond",
      "The pitfalls of expectation",
      "A story in motion",
    ],
    group: "t2",
  },
  {
    slug: "solitude",
    title: "Solitude",
    price: "$9.50",
    image: "/solitude.jpg",
    summary: "Understand solitude as a tension between blending in and transforming. Reopen encounter.",
    chapters: [
      "Introduction",
      "The misunderstanding of lack",
      "Blending in or transforming",
      "Shaping the world in one’s image",
      "Encountering otherness",
      "Creativity and new connections",
      "Concrete steps",
      "Conclusion",
    ],
    group: "t2",
  },
  {
    slug: "tdah",
    title: "ADHD",
    price: "$9.50",
    image: "/tdah.jpg",
    summary: "A singular way of desire and time. Turn tension into creative drive.",
    chapters: [
      "Introduction",
      "A singular functioning",
      "When daily life speaks",
      "Markers to situate yourself",
      "Finding your own rhythm",
      "Turning tension into a motor",
      "Relationships and desire",
      "Next steps",
      "Conclusion?",
    ],
    group: "t1",
  },
  {
    slug: "tsa",
    title: "Autistic spectrum disorders",
    price: "$9.50",
    image: "/tsa.jpg",
    summary: "Regain a hold on life: markers, dialogue, and invention of forms of bond and environment.",
    chapters: [
      "Regaining a hold on life",
      "Perceiving differently",
      "Creating your markers",
      "Learning to dialogue",
      "Transforming relationships",
      "Opening to the world",
      "Evolving your environment",
      "A singular and creative path",
    ],
    group: "t1",
  },
  {
    slug: "tca",
    title: "Eating disorders",
    price: "$9.50",
    image: "/tca.jpg",
    summary: "Beyond food: struggle with the void, the body, and desire. Recover vital movement.",
    chapters: [
      "Introduction",
      "Eating the void or the overflow of the void",
      "Withdrawal and disinvestment from the world",
      "Refusal of the sexed body and fear of desire",
      "From the whole to the part: endless fixation",
      "The illusory power of “nothing”",
      "Recovering the movement of desire",
      "Paths of support and conclusion",
    ],
    group: "t1",
  },
  {
    slug: "sommeil",
    title: "Sleep disorders",
    price: "$9.50",
    image: "/sommeil.jpg",
    summary: "Rhythms, stress, emotions, and environment: concrete paths toward a peaceful night.",
    chapters: [
      "Introduction",
      "Body, mind, and biological rhythms",
      "Stress, anxiety, and rumination",
      "Habits and environment",
      "Sleep and deep emotions",
      "Ways to regain your rhythm",
      "When sleep speaks",
      "Toward a peaceful relationship with the night",
    ],
    group: "t1",
  },
  {
    slug: "procrastination-creativite",
    title: "Procrastination and creativity",
    price: "$9.50",
    image: "/procrastination.jpg",
    summary: "From avoidance to invention: starting as a creative act, valuing boredom and multiple beginnings.",
    chapters: [
      "Introduction",
      "The false excuse of certainty",
      "Starting is already creating",
      "Boredom as a passage",
      "Finding desire in the goal",
      "From avoidance to invention",
      "Concrete tracks",
      "Conclusion",
    ],
    group: "t1",
  },
  {
    slug: "hauts-potentiels",
    title: "High potentials",
    price: "$9.50",
    image: "/hpi.jpg",
    summary: "Beyond IQ: strengths, vulnerabilities, lifestyle and relationships to invent a singular path.",
    chapters: [
      "What HPI means today",
      "A fast and singular mind",
      "Living difference daily",
      "Strengths of HPI",
      "Frequent vulnerabilities",
      "Growing and thriving with HPI",
      "Finding lifestyle and relationships",
      "Inventing your own path",
    ],
    group: "t2",
  },
  {
    slug: "pack-integral",
    title: "Full pack",
    price: "$54.50",
    image: "/pack.jpg",
    summary: "All 11 guides + the Introduction at a reduced price. Full access to work each theme.",
    chapters: [
      "Pack content:",
      "Introduction to the guides",
      "Self-esteem",
      "Depression",
      "Anxiety",
      "Romantical relationships",
      "Solitude",
      "ADHD",
      "Autistic spectrum disorders",
      "Eating disorders",
      "Sleep disorders",
      "Procrastination and creativity",
      "High potentials",
    ],
    group: "t2",
  },
]

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug)
}
